version: '3.7'

services:
  api:
    build: back/application
    ports:
      - 8080:8080
    environment:
      SERVER_SERVLET_CONTEXT_PATH: /api
      SPRING_JPA_OPEN_IN_VIEW: 'false'
      SPRING_DATASOURCE_URL: jdbc:${DB_SYSTEM}://${DB_SERVER}:${DB_PORT}/${DB_SCHEMA}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
